name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '${{ secrets.azurecredetials }}'
          
       
