name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build the tagged Docker image
      run:  |
          docker stop $( docker ps --filter ancestor=$(docker images --filter=reference=travelapi --format "{{.ID}}") --format "{{.ID}}")
        
       
    
    
