name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up SSH connection
        run: |
          ssh-keyscan -H arun-ln-vm.eastus.cloudapp.azure.com >> ~/.ssh/known_hosts
      - name: Copy Docker Compose file to Azure VM
        uses: azure/scp@v1
        with:
          source: ./Travel/docker-compose.yml
          target: /home/username/
          connection: arun-ln-vm.eastus.cloudapp.azure.com
      - name: Run Docker Compose on Azure VM
        run: ssh azureuser@arun-ln-vm.eastus.cloudapp.azure.com "cd /home/username/ && docker-compose up -d"
