name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build the tagged Docker image
      run:  |
          img = docker images --filter=reference=travelapi --format "{{.ID}}"
          cont =  docker ps --filter ancestor= img --format "{{.ID}}"
          docker stop  cont
          docker rm -f cont
          docker rmi img
        
       
    
    
