name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get Images
        echo "docker_tag=$(docker images --filter=reference=travelapi --format "{{.ID}}")" >> $GITHUB_OUTPUT
      
    - name: Get Container
      id  : cont
      run:  |
          echo "docker_con=$(docker ps --filter ancestor=${{steps.img.outputs.docker_tag}})" >> $GITHUB_OUTPUT  
          
 
 

       
    
    
