name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get Images
      id: img
      run :
        echo "docker_tag=$(docker images --filter=reference=travelapi --format "{{.ID}}")" >> $GITHUB_OUTPUT

    - name: Get Cont
      id  : con
      run : |
        echo "docker_con=$(docker ps --filter ancestor=${{steps.img.outputs.docker_tag}} --format "{{.ID}}")" >> $GITHUB_OUTPUT
    
    - name: Print Cont
      run : |
            docker stop ${{steps.con.outputs.docker_con}}
            docker rmi ${{steps.con.outputs.docker_con}}
            
      
 
          
 
 

       
    
    
