name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1 
            
    - name: Compose images and deployment
      run: docker-compose -f "./Travel/docker-compose.yml" up -d --build
            
      
 
          
 
 

       
    
    
