name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get Images
      run :
        echo "docker_tag=$(docker images --filter=reference=travelapi --format "{{.ID}}")" >> $GITHUB_OUTPUT
      
 
          
 
 

       
    
    
