name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get Images
      id  : img
      run:  docker images --filter=reference=travelapi --format "{{.ID}}" 
      
    - name: Set image IDs variable
      env:
        image_ids: ${{ steps.img.outputs.stdout }}


       
    
    
