name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
          
      - name: Build and generate Compose file 
        run: docker-compose -f "./Travel/docker-compose.yml" up -d --build
    
    
