name: Platform-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get Images
      id  : img
      run:  docker images --filter=reference=travelapi --format "{{.ID}}" 
      
    - name: Print Images  
       set-env:
            image_ids: ${{ steps.images.outputs.stdout }}
      
    - name: Read Images  
      run : ${{ env.image_ids }}
       
    
    
